# Generated by Django 4.0.1 on 2022-01-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinventory', '0003_warehouse_item_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('warehouse', 'code')},
        ),
    ]
